"""Report generation from conversation history.

Two report types:
- Incident Summary: structured text for copy-paste into reporting forms
- Solicitor Pack: consultation prep for solicitor-path cases

Provides prompt builders and a section parser. Does NOT call Gemini
directly — the endpoint uses RAGService.query() with these prompts.
"""

import re

from models import ReportSection

# ---------------------------------------------------------------------------
# Solicitor directory by jurisdiction
# ---------------------------------------------------------------------------

_SOLICITOR_LINKS: dict[str, str] = {
    "England and Wales": (
        "- solicitors.lawsociety.org.uk (Law Society Find a Solicitor)\n"
        "- muslimlawyer.co.uk (Muslim Lawyer UK)\n"
        "- muslimsolicitors.co.uk (Muslim Solicitors)"
    ),
    "Scotland": ("- lawscot.org.uk (Law Society of Scotland)\n- muslimlawyer.co.uk (Muslim Lawyer UK)"),
    "Northern Ireland": ("- lawsoc-ni.org (Law Society of Northern Ireland)"),
}


def _build_incident_summary_prompt(jurisdiction: str | None = None) -> str:
    """Build the Gemini prompt for generating an incident summary report."""
    jur_line = f"\nJURISDICTION: {jurisdiction}" if jurisdiction else ""
    return (
        "INSTRUCTION: You are generating a structured INCIDENT REPORT SUMMARY, "
        "NOT having a conversation. Do NOT ask questions. Do NOT request more information. "
        "Use ONLY the information in the conversation history. "
        "If a detail is missing, write 'Not provided' for that section.\n\n"
        "Generate the report in this EXACT format:\n\n"
        "--- INCIDENT REPORT SUMMARY ---\n"
        f"Generated by AskAdil{jur_line}\n\n"
        "TYPE:\n[Religious discrimination / hate crime / online hate — identify from conversation]\n\n"
        "WHAT HAPPENED:\n[Summarise the incident in 2-4 clear sentences from the conversation]\n\n"
        "WHERE THIS HAPPENED:\n[Location if mentioned, otherwise 'Not provided']\n\n"
        "WHEN THIS HAPPENED:\n[Date, time, duration if mentioned, otherwise 'Not provided']\n\n"
        "SUSPECT DESCRIPTION:\n[Any descriptions provided, otherwise 'Not provided']\n\n"
        "POLICE CONTACTED:\n[Yes/No if mentioned, otherwise 'Not provided']\n\n"
        "EVIDENCE:\n[Any URLs, screenshots, or documents mentioned, otherwise 'None mentioned']\n\n"
        "LEGAL CONTEXT:\n[Relevant legislation identified during the conversation, "
        "e.g. Equality Act 2010 s.13, Public Order Act 1986 s.29B, Crime and Disorder Act 1998 s.28]\n\n"
        "--- END REPORT ---"
    )


def _build_solicitor_pack_prompt(jurisdiction: str | None = None) -> str:
    """Build the Gemini prompt for generating a solicitor consultation pack."""
    jur = jurisdiction or "England and Wales"
    solicitor_links = _SOLICITOR_LINKS.get(jur, _SOLICITOR_LINKS["England and Wales"])

    return (
        "INSTRUCTION: You are generating a SOLICITOR CONSULTATION PACK, "
        "NOT having a conversation. Do NOT ask questions. Do NOT request more information. "
        "Use ONLY the information in the conversation history. "
        "If a detail is missing, write 'Not provided' for that section.\n\n"
        "This pack is for the user to bring to their first solicitor appointment.\n\n"
        "Generate the report in this EXACT format:\n\n"
        "--- SOLICITOR CONSULTATION PACK ---\n"
        f"Generated by AskAdil — Jurisdiction: {jur}\n"
        "Bring this to your first solicitor appointment.\n\n"
        "YOUR SITUATION:\n[Structured narrative from conversation — 3-5 sentences]\n\n"
        "KEY DATES:\n"
        "- Incident date: [date if mentioned, otherwise 'Not provided']\n"
        "- Time limit for ET claim: [calculate 3 months less 1 day from incident date if applicable]\n"
        "- ACAS EC must be started by: [calculate if applicable, otherwise 'N/A']\n\n"
        "RELEVANT LEGISLATION:\n[List all relevant Acts and sections identified, "
        "e.g. Equality Act 2010 s.13 (direct discrimination), s.26 (harassment)]\n\n"
        "ASKADIL ASSESSMENT:\n"
        "- Key legal issues identified: [list from conversation]\n"
        "- Note: This is a preliminary AI assessment, not legal advice.\n\n"
        "WHAT TO ASK YOUR SOLICITOR:\n"
        "1. Do I have grounds for a claim?\n"
        "2. Should we go through ACAS Early Conciliation first?\n"
        "3. What evidence do I need to gather?\n"
        "4. Do you offer a no-win-no-fee arrangement for discrimination cases?\n"
        "5. What is the realistic timeline and cost?\n\n"
        "FIND A SOLICITOR:\n"
        f"{solicitor_links}\n\n"
        "--- END PACK ---"
    )


def _build_police_uk_guide_prompt(jurisdiction: str | None = None) -> str:
    """Step-by-step guide for the Police UK hate crime form."""
    return (
        "INSTRUCTION: You are generating a STEP-BY-STEP FORM GUIDE for the Police UK "
        "online hate crime reporting form at https://www.police.uk/ro/report/hate-crime/, "
        "NOT having a conversation. Do NOT ask questions. Do NOT request more information. "
        "Use ONLY the information in the conversation history.\n\n"
        "Generate the guide in this EXACT format:\n\n"
        "--- POLICE UK HATE CRIME FORM GUIDE ---\n"
        "Form URL: https://www.police.uk/ro/report/hate-crime/forms/v1/hate-crime-online2/\n\n"
        "Step 1: Enter your first name and surname\n"
        "[Pre-fill suggestion if available from conversation, otherwise 'Enter your details']\n\n"
        "Step 2: Enter your date of birth\n"
        "[Format: DD/MM/YYYY]\n\n"
        "Step 3: Select your gender\n"
        "[Options: Female, Male, Self-describe]\n\n"
        "Step 4: Describe what happened\n"
        "[Copy-paste text from conversation — summarise the incident in 2-4 sentences]\n\n"
        "Step 5: Enter where the incident happened\n"
        "[Location from conversation, or 'Enter the location']\n\n"
        "Step 6: Enter when the incident happened\n"
        "[Date/time from conversation]\n\n"
        "Step 7: Review and submit\n"
        "[Check all details are correct before submitting]\n\n"
        "--- END GUIDE ---"
    )


def _build_tell_mama_guide_prompt(jurisdiction: str | None = None) -> str:
    """Step-by-step guide for the Tell MAMA report form."""
    return (
        "INSTRUCTION: You are generating a STEP-BY-STEP FORM GUIDE for the Tell MAMA "
        "report form at https://tellmamauk.org/submit-a-report-to-us/, "
        "NOT having a conversation. Do NOT ask questions. Do NOT request more information. "
        "Use ONLY the information in the conversation history.\n\n"
        "Generate the guide in this EXACT format:\n\n"
        "--- TELL MAMA REPORT FORM GUIDE ---\n"
        "Form URL: https://tellmamauk.org/submit-a-report-to-us/\n\n"
        "Step 1: Enter your name\n"
        "[Your full name]\n\n"
        "Step 2: Enter your email address\n"
        "[For Tell MAMA to follow up]\n\n"
        "Step 3: Enter your phone number\n"
        "[Optional but recommended]\n\n"
        "Step 4: Select incident type\n"
        "[Based on conversation: offline/online/institutional anti-Muslim hatred]\n\n"
        "Step 5: Describe what happened\n"
        "[Copy-paste text — detailed description from conversation]\n\n"
        "Step 6: Enter the location\n"
        "[Location from conversation]\n\n"
        "Step 7: Are you the victim or a witness?\n"
        "[Based on conversation context]\n\n"
        "Step 8: Upload any evidence (optional)\n"
        "[Screenshots, photos, or documents if available]\n\n"
        "Step 9: Review and submit\n\n"
        "--- END GUIDE ---"
    )


def _build_police_scotland_guide_prompt(jurisdiction: str | None = None) -> str:
    """Step-by-step guide for the Police Scotland hate crime form."""
    return (
        "INSTRUCTION: You are generating a STEP-BY-STEP FORM GUIDE for the Police Scotland "
        "hate crime reporting form at https://www.scotland.police.uk/secureforms/c3/, "
        "NOT having a conversation. Do NOT ask questions. Do NOT request more information. "
        "Use ONLY the information in the conversation history.\n\n"
        "Generate the guide in this EXACT format:\n\n"
        "--- POLICE SCOTLAND HATE CRIME FORM GUIDE ---\n"
        "Form URL: https://www.scotland.police.uk/secureforms/c3/\n\n"
        "Step 1: Is this an emergency? Select 'No' (unless ongoing threat)\n\n"
        "Step 2: Select 'Hate Related Incident - Religion'\n\n"
        "Step 3: Are you reporting for yourself or someone else?\n"
        "[Based on conversation context]\n\n"
        "Step 4: Do you wish to remain anonymous? Select Yes or No\n\n"
        "Step 5: Enter your personal details (name, address, phone, email)\n\n"
        "Step 6: What happened? (max 2000 characters)\n"
        "[Copy-paste: summarise the incident from conversation]\n\n"
        "Step 7: Where did this happen? (max 2000 characters)\n"
        "[Location from conversation]\n\n"
        "Step 8: When did this happen? (max 2000 characters)\n"
        "[Date/time from conversation]\n\n"
        "Step 9: Description of the person responsible (max 2000 characters)\n"
        "[If available from conversation, otherwise 'Unknown']\n\n"
        "Step 10: Any additional information (max 2000 characters)\n"
        "[Legal context from AskAdil analysis]\n\n"
        "Step 11: Tick the disclaimer checkbox and submit\n\n"
        "--- END GUIDE ---"
    )


def get_report_prompt(report_type: str, jurisdiction: str | None = None) -> str:
    """Return the appropriate prompt for the given report type."""
    if report_type == "solicitor_pack":
        return _build_solicitor_pack_prompt(jurisdiction)
    elif report_type == "police_uk_guide":
        return _build_police_uk_guide_prompt(jurisdiction)
    elif report_type == "tell_mama_guide":
        return _build_tell_mama_guide_prompt(jurisdiction)
    elif report_type == "police_scotland_guide":
        return _build_police_scotland_guide_prompt(jurisdiction)
    return _build_incident_summary_prompt(jurisdiction)


def parse_report_sections(report_text: str) -> list[ReportSection]:
    """Parse a generated report into structured sections.

    Looks for patterns like:
        HEADING:
        Content text here.
    """
    sections: list[ReportSection] = []
    # Match lines like "WHAT HAPPENED:" or "KEY DATES:" followed by content
    pattern = re.compile(
        r"^([A-Z][A-Z\s/()]+):\s*\n(.*?)(?=\n[A-Z][A-Z\s/()]+:\s*\n|---\s|$)",
        re.MULTILINE | re.DOTALL,
    )
    for match in pattern.finditer(report_text):
        heading = match.group(1).strip()
        content = match.group(2).strip()
        if content and heading not in ("INSTRUCTION",):
            sections.append(ReportSection(heading=heading, content=content))
    return sections
