"""create judgments table

Revision ID: f2b5ff000b4e
Revises:
Create Date: 2026-04-05 01:12:00.013180

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2b5ff000b4e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "judgments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("neutral_citation", sa.String(length=100), nullable=False),
        sa.Column("tna_uri", sa.String(length=200), nullable=False),
        sa.Column("tna_url", sa.String(length=500), nullable=False),
        sa.Column("court", sa.String(length=50), nullable=False),
        sa.Column("case_name", sa.String(length=500), nullable=False),
        sa.Column("judgment_date", sa.Date(), nullable=True),
        sa.Column("search_domain", sa.String(length=100), nullable=False),
        sa.Column("search_query", sa.String(length=500), nullable=False),
        sa.Column("raw_xml", sa.Text(), nullable=False),
        sa.Column("clean_text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "UPLOADED", "SKIPPED", "FAILED", name="judgmentstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("gemini_file_id", sa.String(length=200), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "fetched_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("neutral_citation"),
    )
    op.create_index("ix_judgments_court", "judgments", ["court"], unique=False)
    op.create_index("ix_judgments_search_domain", "judgments", ["search_domain"], unique=False)
    op.create_index("ix_judgments_status", "judgments", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_judgments_status", table_name="judgments")
    op.drop_index("ix_judgments_search_domain", table_name="judgments")
    op.drop_index("ix_judgments_court", table_name="judgments")
    op.drop_table("judgments")
    # ### end Alembic commands ###
