"""Tests for report generation prompt builders and section parser."""
import pytest
from report_generator import (
    _build_incident_summary_prompt,
    _build_solicitor_pack_prompt,
    get_report_prompt,
    parse_report_sections,
)


class TestIncidentSummaryPrompt:
    def test_contains_required_sections(self):
        prompt = _build_incident_summary_prompt("England and Wales")
        assert "WHAT HAPPENED" in prompt
        assert "WHERE THIS HAPPENED" in prompt
        assert "WHEN THIS HAPPENED" in prompt
        assert "LEGAL CONTEXT" in prompt
        assert "INCIDENT REPORT SUMMARY" in prompt

    def test_includes_jurisdiction(self):
        prompt = _build_incident_summary_prompt("Scotland")
        assert "Scotland" in prompt

    def test_no_jurisdiction(self):
        prompt = _build_incident_summary_prompt(None)
        assert "JURISDICTION:" not in prompt

    def test_is_instruction_not_conversation(self):
        prompt = _build_incident_summary_prompt()
        assert "NOT having a conversation" in prompt
        assert "Do NOT ask questions" in prompt


class TestSolicitorPackPrompt:
    def test_contains_required_sections(self):
        prompt = _build_solicitor_pack_prompt("England and Wales")
        assert "SOLICITOR CONSULTATION PACK" in prompt
        assert "KEY DATES" in prompt
        assert "RELEVANT LEGISLATION" in prompt
        assert "WHAT TO ASK YOUR SOLICITOR" in prompt
        assert "FIND A SOLICITOR" in prompt

    def test_england_wales_uses_law_society(self):
        prompt = _build_solicitor_pack_prompt("England and Wales")
        assert "solicitors.lawsociety.org.uk" in prompt

    def test_scotland_uses_scottish_resources(self):
        prompt = _build_solicitor_pack_prompt("Scotland")
        assert "lawscot.org.uk" in prompt

    def test_ni_uses_ni_resources(self):
        prompt = _build_solicitor_pack_prompt("Northern Ireland")
        assert "lawsoc-ni.org" in prompt

    def test_defaults_to_england_wales(self):
        prompt = _build_solicitor_pack_prompt(None)
        assert "solicitors.lawsociety.org.uk" in prompt

    def test_is_instruction_not_conversation(self):
        prompt = _build_solicitor_pack_prompt()
        assert "NOT having a conversation" in prompt


class TestGetReportPrompt:
    def test_incident_summary_type(self):
        prompt = get_report_prompt("incident_summary", "England and Wales")
        assert "INCIDENT REPORT SUMMARY" in prompt

    def test_solicitor_pack_type(self):
        prompt = get_report_prompt("solicitor_pack", "Scotland")
        assert "SOLICITOR CONSULTATION PACK" in prompt

    def test_unknown_type_defaults_to_incident(self):
        prompt = get_report_prompt("unknown_type")
        assert "INCIDENT REPORT SUMMARY" in prompt


class TestParseReportSections:
    def test_parse_incident_report(self):
        text = (
            "--- INCIDENT REPORT SUMMARY ---\n"
            "Generated by AskAdil\n\n"
            "WHAT HAPPENED:\nSomeone shouted Islamophobic abuse.\n\n"
            "WHERE THIS HAPPENED:\nBirmingham city centre.\n\n"
            "WHEN THIS HAPPENED:\n15 March 2026, around 3pm.\n\n"
            "LEGAL CONTEXT:\nCrime and Disorder Act 1998 s.28.\n\n"
            "--- END REPORT ---"
        )
        sections = parse_report_sections(text)
        assert len(sections) >= 3
        assert sections[0].heading == "WHAT HAPPENED"
        assert "shouted" in sections[0].content

    def test_parse_solicitor_pack(self):
        text = (
            "--- SOLICITOR CONSULTATION PACK ---\n\n"
            "YOUR SITUATION:\nDenied prayer breaks at work.\n\n"
            "KEY DATES:\nIncident: 10 March 2026\n\n"
            "RELEVANT LEGISLATION:\nEquality Act 2010 s.13\n\n"
            "WHAT TO ASK YOUR SOLICITOR:\n1. Do I have grounds?\n\n"
            "--- END PACK ---"
        )
        sections = parse_report_sections(text)
        assert len(sections) >= 3
        assert any(s.heading == "KEY DATES" for s in sections)
        assert any(s.heading == "RELEVANT LEGISLATION" for s in sections)

    def test_parse_empty_text(self):
        sections = parse_report_sections("")
        assert sections == []

    def test_parse_no_sections(self):
        sections = parse_report_sections("Just some random text without headings.")
        assert sections == []
