"""initial models

Revision ID: e94bb186bea8
Revises:
Create Date: 2026-03-26 22:51:05.582187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e94bb186bea8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("goal", sa.Enum("signup", "booking", "payment", "custom", name="campaign_goal"), nullable=False),
        sa.Column("status", sa.Enum("draft", "active", "paused", "completed", name="campaign_status"), nullable=False),
        sa.Column("templates", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("cadence", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("llm_config", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("research_instructions", sa.Text(), nullable=True),
        sa.Column("compose_instructions", sa.Text(), nullable=True),
        sa.Column("classify_instructions", sa.Text(), nullable=True),
        sa.Column("conversion_config", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("auto_send", sa.Boolean(), nullable=False),
        sa.Column("sender_name", sa.Text(), nullable=True),
        sa.Column("sender_email", sa.Text(), nullable=True),
        sa.Column("reply_to", sa.Text(), nullable=True),
        sa.Column("success_criteria", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("firm_name", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("research_data", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "researching",
                "ready",
                "draft_pending",
                "emailed",
                "replied",
                "converted",
                "declined",
                "unresponsive",
                "bounced",
                name="contact_status",
            ),
            nullable=False,
        ),
        sa.Column("current_cadence_step", sa.Integer(), nullable=False),
        sa.Column("consent", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_contacts_campaign_status", "contacts", ["campaign_id", "status"], unique=False)
    op.create_table(
        "agent_checkpoints",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("graph_name", sa.Text(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("current_node", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_checkpoints_contact_active",
        "agent_checkpoints",
        ["contact_id", "is_active"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_table(
        "conversions",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("signup", "booking", "payment", name="conversion_type"), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_id"),
    )
    op.create_table(
        "outreach_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("(gen_random_uuid())"), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "email_sent",
                "email_opened",
                "email_clicked",
                "reply_received",
                "reply_classified",
                "follow_up_sent",
                "draft_created",
                "draft_approved",
                "signup_completed",
                "booking_made",
                "payment_received",
                "manually_updated",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("channel", sa.Enum("email", "webhook", "manual", "system", name="event_channel"), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_outreach_events_contact_created", "outreach_events", ["contact_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outreach_events_contact_created", table_name="outreach_events")
    op.drop_table("outreach_events")
    op.drop_table("conversions")
    op.drop_index(
        "ix_agent_checkpoints_contact_active",
        table_name="agent_checkpoints",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("agent_checkpoints")
    op.drop_index("ix_contacts_campaign_status", table_name="contacts")
    op.drop_table("contacts")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
